#!/usr/bin/python3

month = input("Enter a month: ")
if (month == "January" or month == "March" or month == "May" or month == "July" or month == "August"  or month == "October" or month == "December"):
    print("The month of " + month + " has 31 days")
else:
    if (month == "April" or month == "June" or month == "September" or month == "November"):
        print("The month of " + month + " has 30 days")
    elif (month == "February"):
            print("The month of " + month + " has 28 or 29 days")
